#+TITLE: Readme

A framework for daily/weekly reviews.

* To try it to see how it works

Create some TODO headlines in ~/tmp/test.org~. Run the following code in
~/tmp/test.org~ (currently there is a bug so the hydra disappears if you don't
do this, otherwise you should be able to call it from anywhere). You will be put
into ~/tmp/test.org~ at the first todo headline. You can mark it as done or add
some tags if you want. Press =n= to go to the next todo. The idea is that you
can make an arbitrary list here mixing org, notmuch, elfeed or other sources and
make the review process seamless.

#+BEGIN_SRC emacs-lisp


(defun el-secretario-test-session ()
  (interactive)
  (el-secretario-start-session
   (list
    (make-el-secretario-source
     :init-function  (lambda () (el-secretario-org-init '(todo) "/tmp/test.org" ))
     :next-function  #'el-secretario-org-next-item
     :prev-function  #'el-secretario-org-previous-item
     :hydra-body #'el-secretario-default-hydra/body
     :finished-hook #'widen
     :next-item-hook (lambda ()
                       (el-secretario-org-add-tag "weeklyreview")))
    (make-el-secretario-source
     :init-function  #'el-secretario--notmuch-init
     :next-function  #'el-secretario--notmuch-show-next-thread
     :prev-function  #'notmuch-show-previous-thread-show
     :hydra-body #'el-secretario-default-hydra/body
     :finished-hook (lambda ())
     :next-item-hook (lambda ()
                       (message "next item"))))))
#+END_SRC

* Each source needs these functions

- A function that is called when initializing a source
- A function for going to the next review item, e.g. next email or nest todo
- A function for going back one review item
- A hydra for actions to do on an item
- A function that is called when a source is finished
- A function that is called when arriving at the next item
